### ISSUE TITLE
Errors on The Fallen Protectors (Siege of Orgrimmar) 

### ISSUE THREAD

**Issue by Xerus2** [BigWigsMods/BigWigs_MistsOfPandaria#17]
1x Found spell 'Meditative Field' using id 143564 on 16, tell the authors!
BigWigs_Core\BossPrototype.lua:1128: in function `UnitDebuff'
...sOfPandaria\SiegeOfOrgrimmar\TheFallenProtectors.lua:136: in function `func'
Decursive\Libs\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <Decursive\Libs\AceTimer-3.0\AceTimer-3.0.lua:50>

Locals:
InCombatSkipped

1x Found spell 'Mark of Anguish' using id 143840 on 16, tell the authors!
BigWigs_Core\BossPrototype.lua:1128: in function `UnitDebuff'
...sOfPandaria\SiegeOfOrgrimmar\TheFallenProtectors.lua:246: in function `?'
BigWigs_Core\BossPrototype.lua:448: in function <BigWigs_Core\BossPrototype.lua:414>

Locals:
InCombatSkipped

2x ...sOfPandaria\SiegeOfOrgrimmar\TheFallenProtectors.lua:349: attempt to perform arithmetic on local 'elapsed' (a nil value)
...sOfPandaria\SiegeOfOrgrimmar\TheFallenProtectors.lua:349: in function `func'
BigWigs_Core\BossPrototype.lua:885: in function <BigWigs_Core\BossPrototype.lua:870>

Locals:
InCombatSkipped

**Comment by funkydude** [comment]
Issue was resolved in https://github.com/BigWigsMods/BigWigs_MistsOfPandaria/commit/b1202df7b9c03906b069b2779e0efee1dae47451
