### ISSUE TITLE
Error when entering Jin'rokh the Breaker's room in Throne of Thunder (tested on Heroic)

### ISSUE THREAD

**Issue by alphabitnz** [BigWigsMods/BigWigs_MistsOfPandaria#21]
1x Invalid spell ID 138375 in the toggleOptions for module BigWigs_Bosses_Jin'rokh the Breaker.
[string "@BigWigs_Core\Core.lua"]:622: in function <BigWigs_Core\Core.lua:555>
[string "@BigWigs_Core\Core.lua"]:643: in function `SetupOptions'
[string "@BigWigs_Core\BossPrototype.lua"]:243: in function `Enable'
[string "@BigWigs_Core\Core.lua"]:121: in function <BigWigs_Core\Core.lua:119>
[string "@BigWigs_Core\Core.lua"]:132: in function <BigWigs_Core\Core.lua:128>
[string "@BigWigs_Core\Core.lua"]:138: in function <BigWigs_Core\Core.lua:136>
[string "@BigWigs_Core\Core.lua"]:152: in function <BigWigs_Core\Core.lua:147>
[string "@BigWigs_Core\Core.lua"]:156: in function `v'
[string "@BigWigs_Core\Core.lua"]:57: in function <BigWigs_Core\Core.lua:54>

**Comment by Mythris29** [comment]
Having the same issue myself.

3x Invalid spell ID 138375 in the toggleOptions for module BigWigs_Bosses_Jin'rokh the Breaker.
[string "@BigWigs_Core\Core.lua"]:625: in function <BigWigs_Core\Core.lua:558>
[string "@BigWigs_Core\Core.lua"]:646: in function `SetupOptions'
[string "@BigWigs_Core\BossPrototype.lua"]:243: in function `Enable'
[string "@BigWigs_Core\Core.lua"]:121: in function <BigWigs_Core\Core.lua:119>
[string "@BigWigs_Core\Core.lua"]:132: in function <BigWigs_Core\Core.lua:128>
[string "@BigWigs_Core\Core.lua"]:138: in function <BigWigs_Core\Core.lua:136>
[string "@BigWigs_Core\Core.lua"]:152: in function <BigWigs_Core\Core.lua:147>
[string "@BigWigs_Core\Core.lua"]:156: in function `v'
[string "@BigWigs_Core\Core.lua"]:57: in function <BigWigs_Core\Core.lua:54>

**Comment by jdcmarques** [comment]
same

1x Invalid spell ID 138375 in the toggleOptions for module BigWigs_Bosses_Jin'rokh the Breaker.
[string "@BigWigs_Core\Core.lua"]:632: in function <BigWigs_Core\Core.lua:565>
[string "@BigWigs_Core\Core.lua"]:653: in function `SetupOptions'
[string "@BigWigs_Core\BossPrototype.lua"]:243: in function `Enable'
[string "@BigWigs_Core\Core.lua"]:121: in function <BigWigs_Core\Core.lua:119>
[string "@BigWigs_Core\Core.lua"]:132: in function <BigWigs_Core\Core.lua:128>
[string "@BigWigs_Core\Core.lua"]:138: in function <BigWigs_Core\Core.lua:136>
[string "@BigWigs_Core\Core.lua"]:152: in function <BigWigs_Core\Core.lua:147>
[string "@BigWigs_Core\Core.lua"]:156: in function `v'
[string "@BigWigs_Core\Core.lua"]:57: in function <BigWigs_Core\Core.lua:54>

**Comment by jdcmarques** [comment]
[23:31] BigWigs: Invalid spell ID 138375 in the toggleOptions for module BigWigs_Bosses_Jin'rokh the Breaker.
[23:31] BigWigs: Module "Jin'rokh the Breaker" tried to register an invalid spell id (138375) to event "SPELL_DAMAGE".
