### ISSUE TITLE
Siege of Orgrimmar Garrosh Warmup Timer issues

### ISSUE THREAD

**Issue by Archont1978** [BigWigsMods/BigWigs_MistsOfPandaria#27]
The newly added warmup timer seem to cause a DC when using "Scroll of Past Deeds" to teleport directly to Garrosh. Have tried with nothing but BigWigs active and still get DC everytime.

**Comment by funkydude** [comment]
Your report is appreciated, but there is a zero chance this is related to BigWigs.

You can try disabling BigWigs and seeing if the issue still occurs, or waiting for another day to see if it's a server issue.
