### ISSUE TITLE
Malkorok giving errors

### ISSUE THREAD

**Issue by glassleo** [BigWigsMods/BigWigs_MistsOfPandaria#3]
During Malkorok Mythic, BigWigs is throwing enough errors that the game asks if I want to disable the AddOn. Please fix?

**Comment by funkydude** [comment]
Not unless you report the errors, no.

Use an addon like BugSack to see addon errors.

**Comment by glassleo** [comment]
I'm pretty sure it's the Arcing Smash radar thing that shows up on Malkorok. I'll try to get some error messages next time I'm there.

**Comment by funkydude** [comment]
I'm not aware of what radar you are referring to.

**Comment by funkydude** [comment]
No response, closing.
